---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podtato
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./podtato/chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: instavote
  interval: 10m0s
  targetNamespace: instavote
